#!/bin/sh

echo "#"
echo "# Warning:"
echo "# prelude-adduser is deprecated and will be removed"
echo "# in the next stable release. "
echo "# Please use 'prelude-admin' instead."
echo "#"

prelude-admin $@
