# Copyright (C) 2003 Nicolas Delon <delon.nicolas@wanadoo.fr>
# All Rights Reserved
#
# This file is part of the Prelude program.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

package GenerateIDMEFTreeToStringH;

use Generate;
@ISA = qw/Generate/;

use strict;
use IDMEFTree; 

sub	header
{
    my	$self = shift;

    $self->output("
/* Auto-generated by the GenerateIDMEFTreeToStringH package */

#ifndef _LIBPRELUDE_IDMEF_TREE_TO_STRING_H
#define _LIBPRELUDE_IDMEF_TREE_TO_STRING_H

");
}

sub	struct
{
    my	$self = shift;
    my	$tree = shift;
    my	$struct = shift;

    $self->output("
int idmef_$struct->{short_typename}_to_string($struct->{typename} *ptr, char *buffer, size_t size);");
}

sub	footer
{
    my	$self = shift;
    my	$tree = shift;

    $self->output("

#endif /* _LIBPRELUDE_IDMEF_TREE_TO_STRING_H */
"
);
}

1;
