
/* Auto-generated by the GenerateIDMEFTreeData package (Sat Dec 13 17:03:59 2003) */

typedef struct {
	char *name;
	int list;
	idmef_value_type_id_t type;
	idmef_type_t object_type;
} children_list_t;

children_list_t idmef_additional_data_children_list[] = {
        { "type", 0, type_enum, idmef_type_additional_data_type },
        { "meaning", 0, type_string, 0 },
        { "data", 0, type_data, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_classification_children_list[] = {
        { "origin", 0, type_enum, idmef_type_classification_origin },
        { "name", 0, type_string, 0 },
        { "url", 0, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_userid_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "type", 0, type_enum, idmef_type_userid_type },
        { "name", 0, type_string, 0 },
        { "number", 0, type_uint32, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_user_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "category", 0, type_enum, idmef_type_user_category },
        { "userid", 1, type_object, idmef_type_userid },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_address_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "category", 0, type_enum, idmef_type_address_category },
        { "vlan_name", 0, type_string, 0 },
        { "vlan_num", 0, type_uint32, 0 },
        { "address", 0, type_string, 0 },
        { "netmask", 0, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_process_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "name", 0, type_string, 0 },
        { "pid", 0, type_uint32, 0 },
        { "path", 0, type_string, 0 },
        { "arg", 1, type_string, 0 },
        { "env", 1, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_webservice_children_list[] = {
        { "url", 0, type_string, 0 },
        { "cgi", 0, type_string, 0 },
        { "http_method", 0, type_string, 0 },
        { "arg", 1, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_snmpservice_children_list[] = {
        { "oid", 0, type_string, 0 },
        { "community", 0, type_string, 0 },
        { "command", 0, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_service_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "name", 0, type_string, 0 },
        { "port", 0, type_uint16, 0 },
        { "portlist", 0, type_string, 0 },
        { "protocol", 0, type_string, 0 },
        { "type", 0, type_enum, idmef_type_service_type },
        { "web", 0, type_object, idmef_type_webservice },
        { "snmp", 0, type_object, idmef_type_snmpservice },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_node_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "category", 0, type_enum, idmef_type_node_category },
        { "location", 0, type_string, 0 },
        { "name", 0, type_string, 0 },
        { "address", 1, type_object, idmef_type_address },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_source_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "spoofed", 0, type_enum, idmef_type_spoofed },
        { "interface", 0, type_string, 0 },
        { "node", 0, type_object, idmef_type_node },
        { "user", 0, type_object, idmef_type_user },
        { "process", 0, type_object, idmef_type_process },
        { "service", 0, type_object, idmef_type_service },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_file_access_children_list[] = {
        { "userid", 0, type_object, idmef_type_userid },
        { "permission", 1, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_inode_children_list[] = {
        { "change_time", 0, type_time, 0 },
        { "number", 0, type_uint32, 0 },
        { "major_device", 0, type_uint32, 0 },
        { "minor_device", 0, type_uint32, 0 },
        { "c_major_device", 0, type_uint32, 0 },
        { "c_minor_device", 0, type_uint32, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_file_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "category", 0, type_enum, idmef_type_file_category },
        { "fstype", 0, type_string, 0 },
        { "name", 0, type_string, 0 },
        { "path", 0, type_string, 0 },
        { "create_time", 0, type_time, 0 },
        { "modify_time", 0, type_time, 0 },
        { "access_time", 0, type_time, 0 },
        { "data_size", 0, type_uint32, 0 },
        { "disk_size", 0, type_uint32, 0 },
        { "file_access", 1, type_object, idmef_type_file_access },
        { "file_linkage", 1, type_object, idmef_type_linkage },
        { "inode", 0, type_object, idmef_type_inode },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_linkage_children_list[] = {
        { "category", 0, type_enum, idmef_type_linkage_category },
        { "name", 0, type_string, 0 },
        { "path", 0, type_string, 0 },
        { "file", 0, type_object, idmef_type_file },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_target_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "decoy", 0, type_enum, idmef_type_spoofed },
        { "interface", 0, type_string, 0 },
        { "node", 0, type_object, idmef_type_node },
        { "user", 0, type_object, idmef_type_user },
        { "process", 0, type_object, idmef_type_process },
        { "service", 0, type_object, idmef_type_service },
        { "file", 1, type_object, idmef_type_file },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_analyzer_children_list[] = {
        { "analyzerid", 0, type_uint64, 0 },
        { "manufacturer", 0, type_string, 0 },
        { "model", 0, type_string, 0 },
        { "version", 0, type_string, 0 },
        { "class", 0, type_string, 0 },
        { "ostype", 0, type_string, 0 },
        { "osversion", 0, type_string, 0 },
        { "node", 0, type_object, idmef_type_node },
        { "process", 0, type_object, idmef_type_process },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_alertident_children_list[] = {
        { "alertident", 0, type_uint64, 0 },
        { "analyzerid", 0, type_uint64, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_impact_children_list[] = {
        { "severity", 0, type_enum, idmef_type_impact_severity },
        { "completion", 0, type_enum, idmef_type_impact_completion },
        { "type", 0, type_enum, idmef_type_impact_type },
        { "description", 0, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_action_children_list[] = {
        { "category", 0, type_enum, idmef_type_action_category },
        { "description", 0, type_string, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_confidence_children_list[] = {
        { "rating", 0, type_enum, idmef_type_confidence_rating },
        { "confidence", 0, type_float, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_assessment_children_list[] = {
        { "impact", 0, type_object, idmef_type_impact },
        { "action", 1, type_object, idmef_type_action },
        { "confidence", 0, type_object, idmef_type_confidence },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_tool_alert_children_list[] = {
        { "name", 0, type_string, 0 },
        { "command", 0, type_string, 0 },
        { "alertident", 1, type_object, idmef_type_alertident },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_correlation_alert_children_list[] = {
        { "name", 0, type_string, 0 },
        { "alertident", 1, type_object, idmef_type_alertident },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_overflow_alert_children_list[] = {
        { "program", 0, type_string, 0 },
        { "size", 0, type_uint32, 0 },
        { "buffer", 0, type_data, 0 },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_alert_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "assessment", 0, type_object, idmef_type_assessment },
        { "analyzer", 0, type_object, idmef_type_analyzer },
        { "create_time", 0, type_time, 0 },
        { "detect_time", 0, type_time, 0 },
        { "analyzer_time", 0, type_time, 0 },
        { "source", 1, type_object, idmef_type_source },
        { "target", 1, type_object, idmef_type_target },
        { "classification", 1, type_object, idmef_type_classification },
        { "additional_data", 1, type_object, idmef_type_additional_data },
        { "type", 0, type_enum, idmef_type_alert_type },
        { "tool_alert", 0, type_object, idmef_type_tool_alert },
        { "correlation_alert", 0, type_object, idmef_type_correlation_alert },
        { "overflow_alert", 0, type_object, idmef_type_overflow_alert },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_heartbeat_children_list[] = {
        { "ident", 0, type_uint64, 0 },
        { "analyzer", 0, type_object, idmef_type_analyzer },
        { "create_time", 0, type_time, 0 },
        { "analyzer_time", 0, type_time, 0 },
        { "additional_data", 1, type_object, idmef_type_additional_data },
        { NULL, 0, 0, 0 }
};

children_list_t idmef_message_children_list[] = {
        { "version", 0, type_string, 0 },
        { "type", 0, type_enum, idmef_type_message_type },
        { "alert", 0, type_object, idmef_type_alert },
        { "heartbeat", 0, type_object, idmef_type_heartbeat },
        { NULL, 0, 0, 0 }
};


typedef struct {
	char *name;
	children_list_t *children_list;
	void *(*get_child)(void *ptr, idmef_child_t child);
	void *(*new_child)(void *ptr, idmef_child_t child, int n);
	int (*to_numeric)(const char *name);
	const char *(*to_string)(int val);
} object_data_t;


object_data_t object_data[] = {
        { "(unassigned)", NULL, NULL, NULL }, /* ID: 0 */
        { "(unassigned)", NULL, NULL, NULL }, /* ID: 1 */
        { "(unassigned)", NULL, NULL, NULL }, /* ID: 2 */
        { "additional_data_type", NULL, NULL, NULL, idmef_additional_data_type_to_numeric, idmef_additional_data_type_to_string}, /* ID: 3 */
        { "additional_data", idmef_additional_data_children_list, idmef_additional_data_get_child, idmef_additional_data_new_child, NULL, NULL }, /* ID: 4 */
        { "classification_origin", NULL, NULL, NULL, idmef_classification_origin_to_numeric, idmef_classification_origin_to_string}, /* ID: 5 */
        { "classification", idmef_classification_children_list, idmef_classification_get_child, idmef_classification_new_child, NULL, NULL }, /* ID: 6 */
        { "userid_type", NULL, NULL, NULL, idmef_userid_type_to_numeric, idmef_userid_type_to_string}, /* ID: 7 */
        { "userid", idmef_userid_children_list, idmef_userid_get_child, idmef_userid_new_child, NULL, NULL }, /* ID: 8 */
        { "user_category", NULL, NULL, NULL, idmef_user_category_to_numeric, idmef_user_category_to_string}, /* ID: 9 */
        { "user", idmef_user_children_list, idmef_user_get_child, idmef_user_new_child, NULL, NULL }, /* ID: 10 */
        { "address_category", NULL, NULL, NULL, idmef_address_category_to_numeric, idmef_address_category_to_string}, /* ID: 11 */
        { "address", idmef_address_children_list, idmef_address_get_child, idmef_address_new_child, NULL, NULL }, /* ID: 12 */
        { "process", idmef_process_children_list, idmef_process_get_child, idmef_process_new_child, NULL, NULL }, /* ID: 13 */
        { "webservice", idmef_webservice_children_list, idmef_webservice_get_child, idmef_webservice_new_child, NULL, NULL }, /* ID: 14 */
        { "snmpservice", idmef_snmpservice_children_list, idmef_snmpservice_get_child, idmef_snmpservice_new_child, NULL, NULL }, /* ID: 15 */
        { "service_type", NULL, NULL, NULL, idmef_service_type_to_numeric, idmef_service_type_to_string}, /* ID: 16 */
        { "service", idmef_service_children_list, idmef_service_get_child, idmef_service_new_child, NULL, NULL }, /* ID: 17 */
        { "node_category", NULL, NULL, NULL, idmef_node_category_to_numeric, idmef_node_category_to_string}, /* ID: 18 */
        { "node", idmef_node_children_list, idmef_node_get_child, idmef_node_new_child, NULL, NULL }, /* ID: 19 */
        { "spoofed", NULL, NULL, NULL, idmef_spoofed_to_numeric, idmef_spoofed_to_string}, /* ID: 20 */
        { "source", idmef_source_children_list, idmef_source_get_child, idmef_source_new_child, NULL, NULL }, /* ID: 21 */
        { "file_access", idmef_file_access_children_list, idmef_file_access_get_child, idmef_file_access_new_child, NULL, NULL }, /* ID: 22 */
        { "inode", idmef_inode_children_list, idmef_inode_get_child, idmef_inode_new_child, NULL, NULL }, /* ID: 23 */
        { "file_category", NULL, NULL, NULL, idmef_file_category_to_numeric, idmef_file_category_to_string}, /* ID: 24 */
        { "file", idmef_file_children_list, idmef_file_get_child, idmef_file_new_child, NULL, NULL }, /* ID: 25 */
        { "linkage_category", NULL, NULL, NULL, idmef_linkage_category_to_numeric, idmef_linkage_category_to_string}, /* ID: 26 */
        { "linkage", idmef_linkage_children_list, idmef_linkage_get_child, idmef_linkage_new_child, NULL, NULL }, /* ID: 27 */
        { "target", idmef_target_children_list, idmef_target_get_child, idmef_target_new_child, NULL, NULL }, /* ID: 28 */
        { "analyzer", idmef_analyzer_children_list, idmef_analyzer_get_child, idmef_analyzer_new_child, NULL, NULL }, /* ID: 29 */
        { "alertident", idmef_alertident_children_list, idmef_alertident_get_child, idmef_alertident_new_child, NULL, NULL }, /* ID: 30 */
        { "impact_severity", NULL, NULL, NULL, idmef_impact_severity_to_numeric, idmef_impact_severity_to_string}, /* ID: 31 */
        { "impact_completion", NULL, NULL, NULL, idmef_impact_completion_to_numeric, idmef_impact_completion_to_string}, /* ID: 32 */
        { "impact_type", NULL, NULL, NULL, idmef_impact_type_to_numeric, idmef_impact_type_to_string}, /* ID: 33 */
        { "impact", idmef_impact_children_list, idmef_impact_get_child, idmef_impact_new_child, NULL, NULL }, /* ID: 34 */
        { "action_category", NULL, NULL, NULL, idmef_action_category_to_numeric, idmef_action_category_to_string}, /* ID: 35 */
        { "action", idmef_action_children_list, idmef_action_get_child, idmef_action_new_child, NULL, NULL }, /* ID: 36 */
        { "confidence_rating", NULL, NULL, NULL, idmef_confidence_rating_to_numeric, idmef_confidence_rating_to_string}, /* ID: 37 */
        { "confidence", idmef_confidence_children_list, idmef_confidence_get_child, idmef_confidence_new_child, NULL, NULL }, /* ID: 38 */
        { "assessment", idmef_assessment_children_list, idmef_assessment_get_child, idmef_assessment_new_child, NULL, NULL }, /* ID: 39 */
        { "tool_alert", idmef_tool_alert_children_list, idmef_tool_alert_get_child, idmef_tool_alert_new_child, NULL, NULL }, /* ID: 40 */
        { "correlation_alert", idmef_correlation_alert_children_list, idmef_correlation_alert_get_child, idmef_correlation_alert_new_child, NULL, NULL }, /* ID: 41 */
        { "overflow_alert", idmef_overflow_alert_children_list, idmef_overflow_alert_get_child, idmef_overflow_alert_new_child, NULL, NULL }, /* ID: 42 */
        { "alert_type", NULL, NULL, NULL, idmef_alert_type_to_numeric, idmef_alert_type_to_string}, /* ID: 43 */
        { "alert", idmef_alert_children_list, idmef_alert_get_child, idmef_alert_new_child, NULL, NULL }, /* ID: 44 */
        { "heartbeat", idmef_heartbeat_children_list, idmef_heartbeat_get_child, idmef_heartbeat_new_child, NULL, NULL }, /* ID: 45 */
        { "message_type", NULL, NULL, NULL, idmef_message_type_to_numeric, idmef_message_type_to_string}, /* ID: 46 */
        { "message", idmef_message_children_list, idmef_message_get_child, idmef_message_new_child, NULL, NULL }, /* ID: 47 */
        { NULL, NULL, NULL, NULL }
};
