
/* Auto-generated by the GenerateIDMEFMessageSendH package (Sun Dec 14 15:48:01 2003) */

#ifndef _LIBPRELUDE_IDMEF_MESSAGE_SEND_H
#define _LIBPRELUDE_IDMEF_MESSAGE_SEND_H

void idmef_send_time(prelude_msgbuf_t *msg, uint8_t tag, idmef_time_t *data);
void idmef_send_additional_data(prelude_msgbuf_t *msg, idmef_additional_data_t *additional_data);
void idmef_send_classification(prelude_msgbuf_t *msg, idmef_classification_t *classification);
void idmef_send_userid(prelude_msgbuf_t *msg, idmef_userid_t *userid);
void idmef_send_user(prelude_msgbuf_t *msg, idmef_user_t *user);
void idmef_send_address(prelude_msgbuf_t *msg, idmef_address_t *address);
void idmef_send_process(prelude_msgbuf_t *msg, idmef_process_t *process);
void idmef_send_webservice(prelude_msgbuf_t *msg, idmef_webservice_t *webservice);
void idmef_send_snmpservice(prelude_msgbuf_t *msg, idmef_snmpservice_t *snmpservice);
void idmef_send_service(prelude_msgbuf_t *msg, idmef_service_t *service);
void idmef_send_node(prelude_msgbuf_t *msg, idmef_node_t *node);
void idmef_send_source(prelude_msgbuf_t *msg, idmef_source_t *source);
void idmef_send_file_access(prelude_msgbuf_t *msg, idmef_file_access_t *file_access);
void idmef_send_inode(prelude_msgbuf_t *msg, idmef_inode_t *inode);
void idmef_send_file(prelude_msgbuf_t *msg, idmef_file_t *file);
void idmef_send_linkage(prelude_msgbuf_t *msg, idmef_linkage_t *linkage);
void idmef_send_target(prelude_msgbuf_t *msg, idmef_target_t *target);
void idmef_send_analyzer(prelude_msgbuf_t *msg, idmef_analyzer_t *analyzer);
void idmef_send_alertident(prelude_msgbuf_t *msg, idmef_alertident_t *alertident);
void idmef_send_impact(prelude_msgbuf_t *msg, idmef_impact_t *impact);
void idmef_send_action(prelude_msgbuf_t *msg, idmef_action_t *action);
void idmef_send_confidence(prelude_msgbuf_t *msg, idmef_confidence_t *confidence);
void idmef_send_assessment(prelude_msgbuf_t *msg, idmef_assessment_t *assessment);
void idmef_send_tool_alert(prelude_msgbuf_t *msg, idmef_tool_alert_t *tool_alert);
void idmef_send_correlation_alert(prelude_msgbuf_t *msg, idmef_correlation_alert_t *correlation_alert);
void idmef_send_overflow_alert(prelude_msgbuf_t *msg, idmef_overflow_alert_t *overflow_alert);
void idmef_send_alert(prelude_msgbuf_t *msg, idmef_alert_t *alert);
void idmef_send_heartbeat(prelude_msgbuf_t *msg, idmef_heartbeat_t *heartbeat);
void idmef_send_message(prelude_msgbuf_t *msg, idmef_message_t *message);

#endif /* _LIBPRELUDE_IDMEF_MESSAGE_SEND_H */
