
/* Auto-generated by the GenerateIDMEFMessageWriteH package */

#ifndef _LIBPRELUDE_IDMEF_MESSAGE_WRITE_H
#define _LIBPRELUDE_IDMEF_MESSAGE_WRITE_H

#include "prelude-inttypes.h"
#include "idmef-time.h"
#include "prelude-string.h"
#include "prelude-message-buffered.h"


void idmef_time_write(idmef_time_t *data, prelude_msgbuf_t *msg, uint8_t tag);
void idmef_additional_data_write(idmef_additional_data_t *additional_data, prelude_msgbuf_t *msg);
void idmef_reference_write(idmef_reference_t *reference, prelude_msgbuf_t *msg);
void idmef_classification_write(idmef_classification_t *classification, prelude_msgbuf_t *msg);
void idmef_user_id_write(idmef_user_id_t *user_id, prelude_msgbuf_t *msg);
void idmef_user_write(idmef_user_t *user, prelude_msgbuf_t *msg);
void idmef_address_write(idmef_address_t *address, prelude_msgbuf_t *msg);
void idmef_process_write(idmef_process_t *process, prelude_msgbuf_t *msg);
void idmef_web_service_write(idmef_web_service_t *web_service, prelude_msgbuf_t *msg);
void idmef_snmp_service_write(idmef_snmp_service_t *snmp_service, prelude_msgbuf_t *msg);
void idmef_service_write(idmef_service_t *service, prelude_msgbuf_t *msg);
void idmef_node_write(idmef_node_t *node, prelude_msgbuf_t *msg);
void idmef_source_write(idmef_source_t *source, prelude_msgbuf_t *msg);
void idmef_file_access_write(idmef_file_access_t *file_access, prelude_msgbuf_t *msg);
void idmef_inode_write(idmef_inode_t *inode, prelude_msgbuf_t *msg);
void idmef_checksum_write(idmef_checksum_t *checksum, prelude_msgbuf_t *msg);
void idmef_file_write(idmef_file_t *file, prelude_msgbuf_t *msg);
void idmef_linkage_write(idmef_linkage_t *linkage, prelude_msgbuf_t *msg);
void idmef_target_write(idmef_target_t *target, prelude_msgbuf_t *msg);
void idmef_analyzer_write(idmef_analyzer_t *analyzer, prelude_msgbuf_t *msg);
void idmef_alertident_write(idmef_alertident_t *alertident, prelude_msgbuf_t *msg);
void idmef_impact_write(idmef_impact_t *impact, prelude_msgbuf_t *msg);
void idmef_action_write(idmef_action_t *action, prelude_msgbuf_t *msg);
void idmef_confidence_write(idmef_confidence_t *confidence, prelude_msgbuf_t *msg);
void idmef_assessment_write(idmef_assessment_t *assessment, prelude_msgbuf_t *msg);
void idmef_tool_alert_write(idmef_tool_alert_t *tool_alert, prelude_msgbuf_t *msg);
void idmef_correlation_alert_write(idmef_correlation_alert_t *correlation_alert, prelude_msgbuf_t *msg);
void idmef_overflow_alert_write(idmef_overflow_alert_t *overflow_alert, prelude_msgbuf_t *msg);
void idmef_alert_write(idmef_alert_t *alert, prelude_msgbuf_t *msg);
void idmef_heartbeat_write(idmef_heartbeat_t *heartbeat, prelude_msgbuf_t *msg);
void idmef_message_write(idmef_message_t *message, prelude_msgbuf_t *msg);

#endif /* _LIBPRELUDE_IDMEF_MESSAGE_WRITE_H */
