/*
 * This enclose an option.
 */
#define PRELUDE_OPTION_START 0
#define PRELUDE_OPTION_END   1

#define PRELUDE_OPTION_NAME  2
#define PRELUDE_OPTION_DESC  3
#define PRELUDE_OPTION_HAS_ARG 4
#define PRELUDE_OPTION_HELP 5
#define PRELUDE_OPTION_INPUT_VALIDATION 6
#define PRELUDE_OPTION_INPUT_TYPE 7

#define PRELUDE_OPTION_ARG 8

